### ISSUE TITLE
How to add a data fixture for GridFS?

### ISSUE THREAD

**Issue by lvarayut** [mgan59/mongoose-fixture#23]
First of all, thanks for the great module. I am curious that when I run the `mongoose-fixture --fixture='all' --add`, is there a way I can add `image` files into by DB using `GridFS`?

**Comment by mgan59** [comment]
Someone asked a similar question before.  I believe it is possible, would require some special work in your fixtures to read `image` files into a `buffer` and then figure out which images go with which records.  I haven't tried it yet, but I think it would work.

**Comment by lvarayut** [comment]
Thanks for your response. I will try it.

**Comment by mgan59** [comment]
Might also help.  When you read in files into a buffer you will most likely need to handle the callback, and if you are reading in multiple files I'd recommend using the `async` library.  You can see an example of this in the [tests](https://github.com/mgan59/mongoose-fixture/blob/master/test/fixtures/ProductsUpdateMock.js)

**Comment by lvarayut** [comment]
Perfect example! Thanks so much :)
