### ISSUE TITLE
Improve comment added to generated fixture file / boilerplate

### ISSUE THREAD

**Issue by hal-gh** [mgan59/mongoose-fixture#7]
The boilerplate schema file generates a file that contains a comment such as the following:

``` javascript
/*
 *  File: PlanetStructures.js
 *  Generated by: Mongoose-Fixture (v0.1.3)
 *
 */
```

While the auto-generated config and schema files are self-explanatory from the file names they are created with, there is no way to tell from the contents of the fixtures files, meaning that when one is pasted and shared online, it is not immediately clear which of the 3 types of files it is.

For example:
https://github.com/mgan59/mongoose-fixture/issues/5#issuecomment-25921163

Ideally, the comments for all 3 boilerplates would be amended to be consistent and thus all would include the purpose of the file in the comment, but the fixtures boilerplate is the most important.

I would have submitted a patch for this, but as it's such a trivial change and you may have a preference about how the comment is expressed, I will leave it at this issue/ticket. I hope that's ok! :)

Thanks a lot!

**Comment by mgan59** [comment]
thanks for the suggestion.  will add something.

**Comment by mgan59** [comment]
Added to each boilerplate the following line `Type:<value>`

```
Type: <DataFixture || Config || Schema>
```
